version: '3'
services:
  app:
    build: .
    ports:
      - 3000:3000
    environment:
      - MONGO_URL=mongodb://mongo:27017/list
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
